### ISSUE TITLE
Gradually lower high-level IR to LLVM dialect

### ISSUE THREAD

**Issue by tyb0807** [openxla/iree#16991]
We want to be able to connect our metaprogramming framework to upstream `ExecutionEngine` to actually run and verify the generated code.

Current state: modules written directly in LLVM dialect can be run on `ExecutionEngine`

Acceptance critera: make different flavors of `TiledMatmulTransform` (on tensors) runnable on `ExecutionEngine`

Incremental steps:

```[tasklist]
### Tasks
- [ ] Lower slightly higher level IR (vector or memref) to LLVM dialect on a simple add example
- [ ] Lower simple matmul on memref to LLVM dialect
- [ ] Lower higher level IR (tensor) to LLVM dialect on a simple add example
- [ ] Lower simple matmul on tensor to LLVM dialect
- [ ] Make sure all flavors of matmul (`Matmul`, `TiledMatmul`, `UnrolledMatmul` and `TiledMatmulTransform`) also runnable with `ExecutionEngine`
```
