### ISSUE TITLE
Migrate to GitHub actions

### ISSUE THREAD

**Issue by GMNGeoffrey** [openxla/iree#9855]
We are migrating all our CI to GitHub actions. Here's a list of jobs to burn down. I'm going to make it a checklist rather than a million different issues. You can put your name after a job to claim it.

Kokoro (all configs under `build_tools/kokoro/gcp_ubuntu/`):
- [x] cmake-bazel/linux/x86-swiftshader - gcmn #9927
- [x] cmake-bazel/linux/x86-turing - gcmn #9979
- [x] cmake/baremetal/riscv32 - gcmn #9845
- [x] cmake/linux/x86-swiftshader - gcmn #9877
- [x] cmake/linux/x86-turing - gcmn #9905
- [x] cmake/linux/riscv64 - gcmn #9951
- [x] cmake/linux/x86-swiftshader-asan - suderman #9958
- [x] cmake/android/arm64-v8a - gcmn #10027 and #10028
- [x] bazel/linux/x86-swiftshader/core - gcmn #9980

Buildkite basic:
- [x] tsan - gcmn #9788
- [x] build and test runtime - gcmn #9774
- [x] Samples: build_tools/buildkite/samples.yml
  - [x] wasm samples - gcmn #11466
  - [x] colab - gcmn #11466
  - [x] other samples - gcmn #11466
- [x] Configurations: build_tools/buildkite/cmake/build_configurations.yml
  - [x] tracing - gcmn #11391
  - [x] runtime only - gcmn #9774
  - [x] size-optimized runtime - gcmn #11391
  - [x] gcc - gcmn #11391
  - [x] wasm runtime - scotttodd #10319

Buildkite complicated. These workflows are going to be non-trivial to migrate. @pzread and I will probably need to handle them and will do them last.

- [x] Linux benchmark
- [x] Cuda benchmark
- [x] Android related pipelines (@pzread, see the detailed work list below)

Detailed steps to migrate the Android related pipelines:

- [x] Setup a Pixel-4 runner for testing
- [x] Run Pixel-4 on-device test in Github postubmit (#13024)
- [x] Migrate benchmark tools (#13182, #13176)
- [x] Run Pixel-4 benchmarks in Github postsubmit (#13199)
- [x] Setup temporary shared pre-postsubmit runners for Pixel-6 and Moto X30
- [x] Run Pixel-6 and Moto X30 on-device test in Github postbumit (https://github.com/openxla/iree/pull/13441)
- [x] Remove buildkite `iree-test-android` pipeline
- [x] Run Pixel-6 and Moto X30 benchmarks in Github postsubmit (https://github.com/openxla/iree/pull/13442)
- [x] Check benchmark data (comparing to buildkite pipeline)
  - [x] Check benchmark conversion (Fixes: #13348)
- [x] Announce benchmark migration date
- [x] Stop Buildkite Android pipeline
- [x] Migrate dashboard data
- [x] Enable uploading Android benchmark results from Github CI (https://github.com/openxla/iree/pull/13557)
- [x] Update dashboard filter (https://github.com/google/dana/pull/79)
- [x] Backfill missing data during the migration
- [x] Reconfigure all mobile phones to run Github runner (and separate pre/postsubmit runners)
- [x] Update the docs about CI benchmark (https://github.com/openxla/iree/pull/13624)

**Comment by ScottTodd** [comment]
The [`build_tools/buildkite/samples.yml`](https://github.com/iree-org/iree/blob/main/build_tools/buildkite/samples.yml) pipeline installs the Python packages from https://github.com/iree-org/iree/releases. It probably makes sense to keep that separate from the per-commit pre-submit and post-submit CI workflow, but we still have a few options for how to integrate:

1. Run on a schedule (e.g. once or twice a day, independent of commit or release activity)
2. Run as part of [`.github/workflows/validate_and_publish_release.yml`](https://github.com/iree-org/iree/blob/main/.github/workflows/validate_and_publish_release.yml), as part of the tests that block publishing from draft -> pre-release
    * This would need some changes to how the samples are ran, since draft releases aren't generally visible
    * Diagnosing and fixing issues with this sort of post-submit build configuration could be tricky. Fix-forward afterwards is simpler
3. Trigger at the end of [`.github/workflows/validate_and_publish_release.yml`](https://github.com/iree-org/iree/blob/main/.github/workflows/validate_and_publish_release.yml)

Are there other post-submit builds that we'd want to run, possibly also using the release artifacts?

**Comment by GMNGeoffrey** [comment]
iree-build-configurations has been disabled and archived

**Comment by allieculp** [comment]
@GMNGeoffrey Is this still open?

**Comment by GMNGeoffrey** [comment]
Yes. Android pipelines are still on Buildkite. Che-Yu is working on migrating them

**Comment by GMNGeoffrey** [comment]
Unassigning myself from issues that I'm not actively working on

**Comment by pzread** [comment]
Listed the work list of Android migration in the issue description.

**Comment by pzread** [comment]
Closed as all migration steps have been done. Cleanup tasks are tracked on #11076

**Comment by GMNGeoffrey** [comment]
Thank you for closing out the hard tasks @pzread! I know this sort of thing can be quite toilsome, but I'm happy we now only have to worry about one CI infrastructure (even though I did like Buildkite better :cry:)
